export CPU_ARCH = cortex-m4

# export CFLAGS += -DPART_CC3200
# export CFLAGS += -DSL_PLATFORM_MULTI_THREADED

USEMODULE += cc3200_driverlib

INCLUDES += -I$(RIOTCPU)/$(CPU)/sdk
INCLUDES += -I$(RIOTCPU)/$(CPU)/sdk/driverlib

include $(RIOTMAKE)/arch/cortexm.inc.mk

